//sample JSON (for extracting data)

	{ album_type: 'single',
	  artists: 
	   [ { external_urls: [Object],
	       href: 'https://api.spotify.com/v1/artists/14zDXN8YUB5izEiGujWaFs',
	       id: '14zDXN8YUB5izEiGujWaFs',
	       name: 'Rob Landes',
	       type: 'artist',
	       uri: 'spotify:artist:14zDXN8YUB5izEiGujWaFs' } ],
	  available_markets: 
	   [ 'AD',
	     'AR',
	     'AT',
	     'AU',
	     'BE',
	     'BG',
	     'BO',
	     'BR',
	     'CA',
	     'CH',
	     'CL',
	     'CO',
	     'CR',
	     'CY',
	     'CZ',
	     'DE',
	     'DK',
	     'DO',
	     'EC',
	     'EE',
	     'ES',
	     'FI',
	     'FR',
	     'GB',
	     'GR',
	     'GT',
	     'HK',
	     'HN',
	     'HU',
	     'ID',
	     'IE',
	     'IS',
	     'IT',
	     'JP',
	     'LI',
	     'LT',
	     'LU',
	     'LV',
	     'MC',
	     'MT',
	     'MX',
	     'MY',
	     'NI',
	     'NL',
	     'NO',
	     'NZ',
	     'PA',
	     'PE',
	     'PH',
	     'PL',
	     'PT',
	     'PY',
	     'SE',
	     'SG',
	     'SK',
	     'SV',
	     'TH',
	     'TR',
	     'TW',
	     'US',
	     'UY',
	     'VN' ],
	  external_urls: 
	   { spotify: 'https://open.spotify.com/album/0HwKKi6mnWJmrsulf1ubkd' },
	  href: 'https://api.spotify.com/v1/albums/0HwKKi6mnWJmrsulf1ubkd',
	  id: '0HwKKi6mnWJmrsulf1ubkd',
	  images: 
	   [ { height: 640,
	       url: 'https://i.scdn.co/image/7315868585912a32ff83bcafd264468e96506da2',
	       width: 640 },
	     { height: 300,
	       url: 'https://i.scdn.co/image/1ef8f4c53363fadb86bc15c3c2b5cf85b902fac4',
	       width: 300 },
	     { height: 64,
	       url: 'https://i.scdn.co/image/9e1a7d4373b9967f351ec9fd61c8b5c567037124',
	       width: 64 } ],
	  name: 'I Wonder as I Wander / Oh Come, Oh Come Emmanuel',
	  type: 'album',
	  uri: 'spotify:album:0HwKKi6mnWJmrsulf1ubkd' }

